### ISSUE TITLE
Delivering pam-configs for pam-auth-update (update.sls)

### ISSUE THREAD

**Issue by mrichar1** [saltstack-formulas/pam-formula#1]
Just wondering if there were any plans to add handling of pam-configs templates through this formula? At the moment I'm just using the file module to add templates to /usr/share/pam-configs/ but it would be nice if this could all happen 'in one place'.

Happy to look into writing an update to the formula to achieve this, if it's not on your todo list any time soon. I _think_ the format of a pam-config template is structured enough that it should be easy to map to it from yaml.

**Comment by fintanmm** [comment]
It's on my todo list but I have one or two formula's I need to clean up first. Please do, I'll help out if I can get the chance.
